from setuptools import setup, find_packages #type: ignore

setup(
    name='alphahelix-database-cloud',
    version='0.1.0',
    author='Jeff Chen',
    author_email='jeffchen@alphahelix.com.tw',
    description='For Internal Use Only.',
    # long_description=open('README.md').read(),
    # long_description_content_type='text/markdown',
    url="https://github.com/yahoo168/alphahelix-database-cloud",
    packages=find_packages(),
    install_requires=[
        'Flask',
        'gunicorn',
        "bson==0.5.10",
        "cachetools==5.3.3",
        "certifi==2024.6.2",
        "charset-normalizer==3.3.2",
        "google-api-core==2.19.0",
        "google-auth==2.30.0",
        "google-auth-oauthlib==1.2.0",
        "google-cloud-core==2.4.1",
        "google-cloud-storage==2.17.0",
        "google-crc32c==1.5.0",
        "google-resumable-media==2.7.1",
        "googleapis-common-protos==1.63.1",
        "idna==3.7",
        "oauthlib==3.2.2",
        "proto-plus==1.24.0",
        "protobuf==4.25.3",
        "pyasn1==0.6.0",
        "pyasn1_modules==0.4.0",
        "python-dateutil==2.9.0.post0",
        "requests==2.32.3",
        "requests-oauthlib==2.0.0",
        "rsa==4.9",
        "setuptools==70.1.0",
        "six==1.16.0",
        "urllib3==2.2.2",
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)